country=NZ
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
ap_scan=1

update_config=1
network={
	ssid="bushnet"
	psk=265a1d049fa63140785e342c9b9eab12d5cdde67b88e47d60f5fcb0ac6bddc45
}

network={
    ssid="bushnet"
    psk="feathers"
    priority=2
}

network={
    ssid="Bushnet"
    psk="feathers"
    priority=2
}

