#!/bin/bash

if [[ $EUID -ne 0 ]]; then
    exec sudo -H $0 $@
fi


vdir=~/.local/venvs/rpi-image
log=`mktemp`
trap "rm -f $log" EXIT

function on_error {
    cat $log
    exit 2
}
trap on_error ERR

virtualenv --python /usr/bin/python3 $vdir &>> $log
. $vdir/bin/activate &>> $log
pip install -r requirements.txt &>> $log

trap - ERR

python $@
